# Generated by Django 5.2 on 2025-04-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('interviewed_at', models.DateField(null=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='請輸入1~10')),
                ('review', models.TextField()),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
